[package]
name = "kuberic-mysql-service"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
kuberic-mysql-adapter = { path = "../kuberic-mysql-adapter" }
kuberic-mysql-core = { path = "../kuberic-mysql-core" }
rustix = { version = "1.1.5", features = ["fs"] }

[dev-dependencies]
mysql_async = { version = "=0.37.1", default-features = false, features = ["minimal-rust"] }
tokio = { version = "1", default-features = false, features = ["rt", "macros", "time"] }

[lints]
workspace = true
